Updates: - Redirection of _env script warning about .env not found to stderr - Staging of version file during install to support --version flag of apptools

diff --git a/_env b/_env
--- a/_env
+++ b/_env
@@ -4,7 +4,7 @@
 ENV_FILE="./.env"
 
 if [ ! -f "$ENV_FILE" ]; then # The .env file does not exist
-  echo "Warning: Env file $ENV_FILE not found, skipping env augmentation"
+	echo "Warning: Env file $ENV_FILE not found, skipping env augmentation" >&2
 else
 	# Load each variable in the .env file
 	while IFS= read -r line; do
